version: '3.8'

services:
  app:
    build:
      context: ./project
    entrypoint: ['/app/entrypoint.sh']
    volumes:
      - .:/app
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@db:5432/test

  db:
    build:
      context: ./project/db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    build:
      context: ./client
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - app
